services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - api
  api:
    build:
      context: ../water-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../water-backend:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=agua
      - DB_USERNAME=root
      - DB_PASSWORD=root1234
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=agua
    ports:
      - "3306:3306"
    volumes:
      - dbagua:/var/lib/mysql
volumes:
  dbagua: